version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-dependencies:
        patterns:
          - "*" # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: gomod
    directories: [".", "./.sage", "./cmd/saga"]
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*" # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"

