version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: cmd/saga
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly
