name: Create GitHub Release

on:
  push:
    tags:
      - '*'

permissions: write-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.19

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
