name: release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  generate-api-docs:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: '1.23'
          check-latest: true

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 22

      - name: Generate API Documentation
        run: make generate-api-doc

      - name: Authenticate to GCP prod
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_E_EXTEND_PROD }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: '.'
          glob: 'api_*.pdf'
          destination: 'api-document-bucket'
          process_gcloudignore: false
  release:
    needs: generate-api-docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: '1.23'
          check-latest: true

      - name: Make
        run: make

      - name: Buf Push
        working-directory: proto
        run: make buf-push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Release
        uses: go-semantic-release/action@v1.23
        with:
          allow-initial-development-versions: true
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
