name: Create New Release Tag

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.19

      - name: Make
        run: make

      - name: Buf Push
        working-directory: proto
        run: make buf-push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Release
        uses: go-semantic-release/action@v1.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
